# @format

apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "arangodb"
spec:
  architecture: 
    - arm64
  metrics:
    mode: sidecar
    enabled: true
    tls: false
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"
    prometheus.io/scrape_interval: "5s"
  mode: ActiveFailover
  image: "arangodb/arangodb:3.11.3"
  environment: Production
  externalAccess:
    type: NodePort
  tls:
    caSecretName: None
  dbservers:
    probes:
      livenessProbeSpec:
        timeoutSeconds: 10
    volumeClaimTemplate:
      spec:
        storageClassName: my-local-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        volumeMode: Filesystem
  agents:
    volumeClaimTemplate:
      spec:
        storageClassName: my-local-ssd
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem
