apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arangodb-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - arangodb.cloud.proxyqb.com
    secretName: arangodb-cloud-proxyqb-com-tls
  rules:
    - host: arangodb.cloud.proxyqb.com
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: arangodb-exposed
                port:
                  number: 8529